import type { Roast } from '../types';
import type { AnyVerdict } from '../analysis/types';

export interface RoastTemplate {
  match: (verdict: AnyVerdict) => boolean;
  generate: (verdict: AnyVerdict) => Roast;
}

function roast(severity: Roast['severity'], message: string, advice: string): Roast {
  return { severity, message, advice };
}

export const templates: RoastTemplate[] = [
  // ── Commit Message ──────────────────────────────────────────
  {
    match: v => v.category === 'commit-message' && v.pattern === 'too-short',
    generate: v => roast('savage',
      `"${truncate(v.message, 20)}" — your commit message has fewer characters than a sneeze.`,
      'Write messages that complete: "This commit [does what] because [why]."',
    ),
  },
  {
    match: v => v.category === 'commit-message' && v.pattern === 'too-short',
    generate: () => roast('savage',
      'That commit message is so short, even a haiku would call it lazy.',
      'Aim for at least one full sentence describing the change.',
    ),
  },
  {
    match: v => v.category === 'commit-message' && v.pattern === 'too-short',
    generate: () => roast('medium',
      'Blink and you\'d miss that commit message. Actually, don\'t blink — you\'d still miss it.',
      'Future you will read this log and weep. Give them something to work with.',
    ),
  },
  {
    match: v => v.category === 'commit-message' && v.pattern === 'generic',
    generate: v => roast('medium',
      `"${truncate(v.message, 30)}" — the commit message equivalent of shrugging.`,
      'Be specific: what file/feature changed and why?',
    ),
  },
  {
    match: v => v.category === 'commit-message' && v.pattern === 'generic',
    generate: () => roast('medium',
      'That commit message could apply to literally any commit in history. Impressive in the worst way.',
      'Try: "fix: prevent login redirect loop when session expires".',
    ),
  },
  {
    match: v => v.category === 'commit-message' && v.pattern === 'generic',
    generate: () => roast('mild',
      'Generic commit message detected. Your git log reads like a grocery list written by someone who forgot what they needed.',
      'Describe the specific change, not a vague category.',
    ),
  },
  {
    match: v => v.category === 'commit-message' && v.pattern === 'all-caps',
    generate: () => roast('medium',
      'CAPS LOCK IS NOT A SUBSTITUTE FOR A DESCRIPTIVE COMMIT MESSAGE.',
      'We can feel the frustration, but lowercase + context will age better.',
    ),
  },
  {
    match: v => v.category === 'commit-message' && v.pattern === 'all-caps',
    generate: () => roast('savage',
      'Your commit message sounds like an esports commentator having a breakdown. Deep breaths.',
      'Channel the rage into a clear description of what you fixed.',
    ),
  },
  {
    match: v => v.category === 'commit-message' && v.pattern === 'all-caps',
    generate: () => roast('medium',
      'I can hear you screaming through the terminal. The commit log is not a therapy session.',
      'Calm commit messages make for a readable history.',
    ),
  },
  {
    match: v => v.category === 'commit-message' && v.pattern === 'emoji-only',
    generate: () => roast('mild',
      'Ah yes, the ancient art of communicating entirely through hieroglyphics.',
      'Emojis as prefixes are fine — but the message still needs words.',
    ),
  },
  {
    match: v => v.category === 'commit-message' && v.pattern === 'emoji-only',
    generate: () => roast('medium',
      'Your commit message looks like a text from your 13-year-old cousin.',
      'Add actual words. Your teammates don\'t have your emoji decoder ring.',
    ),
  },
  {
    match: v => v.category === 'commit-message' && v.pattern === 'emoji-only',
    generate: () => roast('mild',
      'Emoji-only commit message. At least pick emojis that describe the change.',
      'Try conventional commits: "feat:", "fix:", "chore:" — emojis optional.',
    ),
  },
  {
    match: v => v.category === 'commit-message' && v.pattern === 'default-message',
    generate: () => roast('mild',
      'You used the default commit message. You know those aren\'t personalized fortunes, right?',
      'Replace auto-generated messages with a description of your actual change.',
    ),
  },
  {
    match: v => v.category === 'commit-message' && v.pattern === 'default-message',
    generate: () => roast('medium',
      'Default commit message spotted. Ctrl+C, Ctrl+V is not a commit strategy.',
      'Write your own message. Even one sentence beats the default.',
    ),
  },
  {
    match: v => v.category === 'commit-message' && v.pattern === 'default-message',
    generate: () => roast('mild',
      'That\'s the default message. The tool wrote it, not you. That\'s... not better.',
      'Take 10 seconds to describe what this commit does.',
    ),
  },
  {
    match: v => v.category === 'commit-message' && v.pattern === 'no-context',
    generate: () => roast('mild',
      'Your commit message is technically words, but barely qualifies as communication.',
      'Add a "because" clause: what changed AND why.',
    ),
  },
  {
    match: v => v.category === 'commit-message' && v.pattern === 'no-context',
    generate: () => roast('mild',
      'That message answers "what" but not "why." Half credit.',
      'Context matters — future readers need to know the motivation.',
    ),
  },
  {
    match: v => v.category === 'commit-message' && v.pattern === 'no-context',
    generate: () => roast('mild',
      'So close to being a real commit message. Just a few more words and you\'d have context.',
      'Aim for 10+ words. Describe the change and its purpose.',
    ),
  },

  // ── Branch Name ─────────────────────────────────────────────
  {
    match: v => v.category === 'branch-name' && v.pattern === 'default-branch',
    generate: v => roast('savage',
      `Pushing directly to ${truncate(v.message, 20)}? That's not bravery, that's a death wish.`,
      'Create a feature branch. Always. No exceptions.',
    ),
  },
  {
    match: v => v.category === 'branch-name' && v.pattern === 'default-branch',
    generate: () => roast('savage',
      'Direct commits to the default branch. Your teammates just felt a disturbance in the force.',
      'Feature branches exist for a reason: code review, CI, and not breaking everything.',
    ),
  },
  {
    match: v => v.category === 'branch-name' && v.pattern === 'default-branch',
    generate: () => roast('savage',
      'Working on main like it\'s a personal project. Spoiler: it\'s not.',
      'Branch off, make your changes, open a PR. This is the way.',
    ),
  },
  {
    match: v => v.category === 'branch-name' && v.pattern === 'meaningless',
    generate: v => roast('medium',
      `"${truncate(v.message, 30)}" — a branch name that tells a story of... absolutely nothing.`,
      'Name branches after the work: feat/user-auth, fix/login-bug.',
    ),
  },
  {
    match: v => v.category === 'branch-name' && v.pattern === 'meaningless',
    generate: () => roast('mild',
      'That branch name is the git equivalent of naming a file "untitled_final_v2_FINAL."',
      'Descriptive names help you and your team find things later.',
    ),
  },
  {
    match: v => v.category === 'branch-name' && v.pattern === 'meaningless',
    generate: () => roast('medium',
      'Your branch name has the specificity of a weather forecast: "things will happen."',
      'Include the ticket number or feature name in the branch.',
    ),
  },
  {
    match: v => v.category === 'branch-name' && v.pattern === 'too-long',
    generate: () => roast('mild',
      'That branch name is longer than most commit messages. Impressive dedication to verbosity.',
      'Keep it under 80 characters. Be descriptive, not exhaustive.',
    ),
  },
  {
    match: v => v.category === 'branch-name' && v.pattern === 'too-long',
    generate: () => roast('mild',
      'Your branch name needs its own scroll bar.',
      'Shorten it. feat/auth-oauth2 beats feat/implement-full-oauth2-authentication-flow-with-refresh-tokens.',
    ),
  },
  {
    match: v => v.category === 'branch-name' && v.pattern === 'too-long',
    generate: () => roast('mild',
      'I ran out of breath reading that branch name.',
      'Abbreviate. Your teammates will thank you when typing it.',
    ),
  },
  {
    match: v => v.category === 'branch-name' && v.pattern === 'bad-characters',
    generate: () => roast('medium',
      'Special characters in a branch name? You enjoy pain, clearly.',
      'Stick to lowercase alphanumeric, hyphens, and slashes.',
    ),
  },
  {
    match: v => v.category === 'branch-name' && v.pattern === 'bad-characters',
    generate: () => roast('medium',
      'That branch name has characters that would make a regex cry.',
      'Use hyphens instead of spaces, avoid brackets and special chars.',
    ),
  },
  {
    match: v => v.category === 'branch-name' && v.pattern === 'bad-characters',
    generate: () => roast('mild',
      'Your branch name has characters that git barely tolerates. Don\'t test its patience.',
      'Safe characters: a-z, 0-9, hyphens, forward slashes.',
    ),
  },
  {
    match: v => v.category === 'branch-name' && v.pattern === 'no-prefix',
    generate: () => roast('mild',
      'No branch prefix? Anarchy has entered the repository.',
      'Try feat/, fix/, chore/ — it makes branch lists scannable.',
    ),
  },
  {
    match: v => v.category === 'branch-name' && v.pattern === 'no-prefix',
    generate: () => roast('mild',
      'A branch without a prefix is like a book without a genre. Technically fine, practically confusing.',
      'Prefixes help categorize work at a glance.',
    ),
  },
  {
    match: v => v.category === 'branch-name' && v.pattern === 'no-prefix',
    generate: () => roast('mild',
      'Your branch doesn\'t follow a naming convention. Wildcard developer detected.',
      'Consider: feat/description, fix/description, chore/description.',
    ),
  },

  // ── Commit Size ─────────────────────────────────────────────
  {
    match: v => v.category === 'commit-size' && v.pattern === 'giant',
    generate: () => roast('savage',
      'That commit is so big it needs its own pull request... and a therapist for the reviewer.',
      'Split into smaller, focused commits. One concern per commit.',
    ),
  },
  {
    match: v => v.category === 'commit-size' && v.pattern === 'giant',
    generate: () => roast('savage',
      'Congratulations, you just committed an entire codebase refactor in one shot. Nobody can review this.',
      'Atomic commits: each one should do one thing and be independently reviewable.',
    ),
  },
  {
    match: v => v.category === 'commit-size' && v.pattern === 'giant',
    generate: () => roast('medium',
      'This commit is less of a commit and more of a code dump. Were you saving up?',
      'Commit more frequently. Smaller diffs are easier to review and revert.',
    ),
  },
  {
    match: v => v.category === 'commit-size' && v.pattern === 'micro',
    generate: () => roast('mild',
      'A single line change gets its own commit? That\'s commitment to... something.',
      'Micro-commits clutter the log. Batch small related changes together.',
    ),
  },
  {
    match: v => v.category === 'commit-size' && v.pattern === 'micro',
    generate: () => roast('mild',
      'Did you just commit a semicolon? This isn\'t a save button.',
      'Wait until you have a meaningful unit of work before committing.',
    ),
  },
  {
    match: v => v.category === 'commit-size' && v.pattern === 'micro',
    generate: () => roast('mild',
      'Your commits are so small they need a microscope to review.',
      'Group related one-liner changes into a single commit.',
    ),
  },
  {
    match: v => v.category === 'commit-size' && v.pattern === 'high-deletion-ratio',
    generate: () => roast('medium',
      'Mass deletion detected. Either you\'re cleaning up or you\'re panicking. I hope it\'s the first one.',
      'Double-check the diff. Make sure you didn\'t delete something you still need.',
    ),
  },
  {
    match: v => v.category === 'commit-size' && v.pattern === 'high-deletion-ratio',
    generate: () => roast('medium',
      'More deletions than insertions? You\'re not writing code, you\'re unwriting it.',
      'Cleanup is valid, but review the deleted code one more time before pushing.',
    ),
  },
  {
    match: v => v.category === 'commit-size' && v.pattern === 'high-deletion-ratio',
    generate: () => roast('mild',
      'Your diff is mostly red. Thanos would approve.',
      'Verify nothing important was caught in the purge.',
    ),
  },

  // ── Risky Actions ───────────────────────────────────────────
  {
    match: v => v.category === 'risky-action' && v.pattern === 'force-push',
    generate: () => roast('savage',
      'Force push detected. You just rewrote history. The git gods are weeping.',
      'Force push only to your own feature branches. Never to shared branches.',
    ),
  },
  {
    match: v => v.category === 'risky-action' && v.pattern === 'force-push',
    generate: () => roast('savage',
      'git push --force: the "hold my beer" of version control.',
      'Use --force-with-lease instead — it at least checks if someone else pushed first.',
    ),
  },
  {
    match: v => v.category === 'risky-action' && v.pattern === 'force-push',
    generate: () => roast('savage',
      'You force-pushed. Somewhere, a teammate\'s local branch just became archaeology.',
      'Coordinate with your team before rewriting shared history.',
    ),
  },
  {
    match: v => v.category === 'risky-action' && v.pattern === 'direct-push-default',
    generate: () => roast('savage',
      'Direct push to the default branch. No PR, no review, no safety net. Just vibes.',
      'Always go through a pull request on shared branches.',
    ),
  },
  {
    match: v => v.category === 'risky-action' && v.pattern === 'direct-push-default',
    generate: () => roast('savage',
      'Pushing straight to main like you\'re the only developer on Earth.',
      'Branch → PR → Review → Merge. This is not optional.',
    ),
  },
  {
    match: v => v.category === 'risky-action' && v.pattern === 'direct-push-default',
    generate: () => roast('medium',
      'Main branch, direct push. Bold. Reckless. Terrifying.',
      'Set up branch protection rules to prevent this.',
    ),
  },
  {
    match: v => v.category === 'risky-action' && v.pattern === 'shared-rebase',
    generate: () => roast('medium',
      'Rebasing a shared branch? You\'re about to create a parallel universe of merge conflicts.',
      'Rebase only your own branches. Use merge for shared branches.',
    ),
  },
  {
    match: v => v.category === 'risky-action' && v.pattern === 'shared-rebase',
    generate: () => roast('savage',
      'Shared branch rebase detected. Every teammate who pulled is now in their own timeline.',
      'Never rebase branches others have based work on.',
    ),
  },
  {
    match: v => v.category === 'risky-action' && v.pattern === 'shared-rebase',
    generate: () => roast('medium',
      'You rebased a branch other people use. Chaos theory in action.',
      'Communicate with your team before rewriting shared history.',
    ),
  },
  {
    match: v => v.category === 'risky-action' && v.pattern === 'delete-remote-branch',
    generate: () => roast('medium',
      'Remote branch deleted. Hope nobody was working on that.',
      'Verify the branch is fully merged before deleting it.',
    ),
  },
  {
    match: v => v.category === 'risky-action' && v.pattern === 'delete-remote-branch',
    generate: () => roast('mild',
      'Branch deleted from remote. Tidying up or covering your tracks?',
      'Clean up merged branches regularly — just make sure they\'re actually merged.',
    ),
  },
  {
    match: v => v.category === 'risky-action' && v.pattern === 'delete-remote-branch',
    generate: () => roast('mild',
      'Remote branch: gone. Reduced to atoms.',
      'Double check with `git branch -r --merged` before cleanup.',
    ),
  },
  {
    match: v => v.category === 'risky-action' && v.pattern === 'hard-reset',
    generate: () => roast('savage',
      'git reset --hard: the nuclear option. Whatever was there is gone now.',
      'Use git stash or create a backup branch before resetting.',
    ),
  },
  {
    match: v => v.category === 'risky-action' && v.pattern === 'hard-reset',
    generate: () => roast('savage',
      'Hard reset. You just told your working directory "I never loved you."',
      'Check git reflog — your changes might still be recoverable.',
    ),
  },
  {
    match: v => v.category === 'risky-action' && v.pattern === 'hard-reset',
    generate: () => roast('medium',
      'Reset --hard detected. Hope you didn\'t need any of those changes.',
      'Prefer git revert for undoing commits — it\'s non-destructive.',
    ),
  },

  // ── Session ─────────────────────────────────────────────────
  {
    match: v => v.category === 'session' && v.pattern === 'long-session',
    generate: () => roast('medium',
      'You\'ve been coding for hours straight. Your brain is running on fumes and vending machine coffee.',
      'Take a break. Tired developers write tired code.',
    ),
  },
  {
    match: v => v.category === 'session' && v.pattern === 'long-session',
    generate: () => roast('medium',
      'Marathon coding session detected. Your error rate doubles after 4 hours.',
      'Step away. The bug will still be there, but you\'ll see it clearly with fresh eyes.',
    ),
  },
  {
    match: v => v.category === 'session' && v.pattern === 'long-session',
    generate: () => roast('mild',
      'That\'s a long session. Even speedrunners take breaks.',
      'Set a timer. 25 min work, 5 min rest. The Pomodoro Technique exists for a reason.',
    ),
  },
  {
    match: v => v.category === 'session' && v.pattern === 'late-night',
    generate: () => roast('medium',
      'Commits at this hour? The code you write at 3 AM is the code you debug at 3 PM.',
      'Sleep is a feature, not a bug. Log off.',
    ),
  },
  {
    match: v => v.category === 'session' && v.pattern === 'late-night',
    generate: () => roast('savage',
      'Late-night commit detected. Your pillow filed a missing persons report.',
      'Nothing good happens in git after midnight.',
    ),
  },
  {
    match: v => v.category === 'session' && v.pattern === 'late-night',
    generate: () => roast('mild',
      'Coding past midnight. You\'ll regret this tomorrow when you read your own code.',
      'Ship it tomorrow with fresh eyes. The deadline isn\'t worth your health.',
    ),
  },
  {
    match: v => v.category === 'session' && v.pattern === 'weekend-warrior',
    generate: () => roast('mild',
      'Weekend commits? Your work-life balance just sent a distress signal.',
      'Unless it\'s a passion project, the code can wait until Monday.',
    ),
  },
  {
    match: v => v.category === 'session' && v.pattern === 'weekend-warrior',
    generate: () => roast('mild',
      'Coding on the weekend. Your friends are at brunch. Just saying.',
      'Burnout is real. Protect your weekends.',
    ),
  },
  {
    match: v => v.category === 'session' && v.pattern === 'weekend-warrior',
    generate: () => roast('mild',
      'Saturday commits. The codebase will survive two days without you.',
      'Rest makes you a better developer. This is scientifically proven.',
    ),
  },
  {
    match: v => v.category === 'session' && v.pattern === 'panic-mode',
    generate: () => roast('savage',
      'Panic commits detected! Multiple commits in rapid succession — who broke prod?',
      'Slow down. Rapid-fire commits usually mean you\'re fixing the fixes.',
    ),
  },
  {
    match: v => v.category === 'session' && v.pattern === 'panic-mode',
    generate: () => roast('savage',
      'Commit. Commit. Commit. Commit. Is everything okay? Blink twice if you need help.',
      'If you\'re hotfixing, take a breath and verify each fix before committing.',
    ),
  },
  {
    match: v => v.category === 'session' && v.pattern === 'panic-mode',
    generate: () => roast('medium',
      'Burst of commits detected. Either you\'re in the zone or in full panic mode.',
      'If panicking: stop, read the error, think, then commit once.',
    ),
  },
];

function truncate(s: string, max: number): string {
  return s.length > max ? s.slice(0, max) + '…' : s;
}
